spring:
  application:
    name: XlsXmanager
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB




logging:
  level:
    it:
      beije:
        xlsxmanager: debug


location:
  directory: src/main/resources/files


